name: prime_sieve
description: A wheel-based prime number sieve. Create a list of primes up to a given value. Fast up to at least 1E9.
version: 0.0.1
homepage: https://github.com/MarcelWaldvogel/Prime-Sieve-Dart/

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  args: ^1.0.0
